Repository kurrent-io/documentation, pull requests merged in 2022-08, with the labels that each got.

#544 add note about insecure servers
  docs/clients/grpc/README.md
Labels: area/grpc, documentation, area/documentation

#548 Adds V22.6 interim release to the docs
  import/repos.json
Labels: area/documentation

#550 Fix Redirect cloud-instance-guidance
  docs/.vuepress/public/_redirects
Labels: area/cloud, area/documentation
